import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/agerestriction">AgeRestriction</Link>
        </li>
        <li>
          <Link to="/audiomusic">AudioMusic</Link>
        </li>
        <li>
          <Link to="/certificationtracking">CertificationTracking</Link>
        </li>
        <li>
          <Link to="/contactus">ContactUs</Link>
        </li>
        <li>
          <Link to="/audittrail">AuditTrail</Link>
        </li>
        <li>
          <Link to="/audiocall">AudioCall</Link>
        </li>
        <li>
          <Link to="/cvresumecandidatemanagement">
            CVResumeCandidateManagement
          </Link>
        </li>
        <li>
          <Link to="/emaillogin">Emaillogin</Link>
        </li>
        <li>
          <Link to="/automatedpublishing">AutomatedPublishing</Link>
        </li>
        <li>
          <Link to="/demoaccount">DemoAccount</Link>
        </li>
        <li>
          <Link to="/imagemanagement">ImageManagement</Link>
        </li>
        <li>
          <Link to="/blogimporting">BlogImporting</Link>
        </li>
        <li>
          <Link to="/audiolibrary">AudioLibrary</Link>
        </li>
        <li>
          <Link to="/fromapprovalworkflow">FromApprovalWorkflow</Link>
        </li>
        <li>
          <Link to="/friendlist">FriendList</Link>
        </li>
        <li>
          <Link to="/blogpostsmanagement">BlogPostsManagement</Link>
        </li>
        <li>
          <Link to="/audioslideshow">AudioSlideShow</Link>
        </li>
        <li>
          <Link to="/leadmanagement">LeadManagement</Link>
        </li>
        <li>
          <Link to="/share">Share</Link>
        </li>
        <li>
          <Link to="/bulkuploading">BulkUploading</Link>
        </li>
        <li>
          <Link to="/callrecording">CallRecording</Link>
        </li>
        <li>
          <Link to="/organisationhierarchy">OrganisationHierarchy</Link>
        </li>
        <li>
          <Link to="/catalogue">Catalogue</Link>
        </li>
        <li>
          <Link to="/playlist">Playlist</Link>
        </li>
        <li>
          <Link to="/switchaccount">SwitchAccount</Link>
        </li>
        <li>
          <Link to="/activityfeed">ActivityFeed</Link>
        </li>
        <li>
          <Link to="/charactercount">CharacterCount</Link>
        </li>
        <li>
          <Link to="/timetrackingbilling">TimeTrackingBilling</Link>
        </li>
        <li>
          <Link to="/addfriends">AddFriends</Link>
        </li>
        <li>
          <Link to="/communityforum">CommunityForum</Link>
        </li>
        <li>
          <Link to="/timesheetmanagement">TimesheetManagement</Link>
        </li>
        <li>
          <Link to="/usergroups">UserGroups</Link>
        </li>
        <li>
          <Link to="/audiovideomessenger">AudioVideoMessenger</Link>
        </li>
        <li>
          <Link to="/contentmanagement">ContentManagement</Link>
        </li>
        <li>
          <Link to="/broadcastmessage">BroadcastMessage</Link>
        </li>
        <li>
          <Link to="/customform">CustomForm</Link>
        </li>
        <li>
          <Link to="/chatbackuprestore">ChatBackupRestore</Link>
        </li>
        <li>
          <Link to="/blogimportingone">BlogImportingOne</Link>
        </li>
        <li>
          <Link to="/videolibrary">VideoLibrary</Link>
        </li>
        <li>
          <Link to="/documentopener">DocumentOpener</Link>
        </li>
        <li>
          <Link to="/googleadsenseintegration">GoogleAdsenseIntegration</Link>
        </li>
        <li>
          <Link to="/documents">Documents</Link>
        </li>
        <li>
          <Link to="/download">Download</Link>
        </li>
        <li>
          <Link to="/draganddrop">Draganddrop</Link>
        </li>
        <li>
          <Link to="/contactsharing">ContactSharing</Link>
        </li>
        <li>
          <Link to="/dynamiccontent">DynamicContent</Link>
        </li>
        <li>
          <Link to="/conversationthreading">ConversationThreading</Link>
        </li>
        <li>
          <Link to="/fileattachment">FileAttachment</Link>
        </li>
        <li>
          <Link to="/importphotoshopdocument">ImportPhotoshopDocument</Link>
        </li>
        <li>
          <Link to="/interactivefaqs">InteractiveFAQs</Link>
        </li>
        <li>
          <Link to="/joblisting">JobListing</Link>
        </li>
        <li>
          <Link to="/library">Library</Link>
        </li>
        <li>
          <Link to="/manageblogcomments">ManageBlogComments</Link>
        </li>
        <li>
          <Link to="/multiselect">MultiSelect</Link>
        </li>
        <li>
          <Link to="/followers">Followers</Link>
        </li>
        <li>
          <Link to="/notes">Notes</Link>
        </li>
        <li>
          <Link to="/pagination">Pagination</Link>
        </li>
        <li>
          <Link to="/paidcontent">PaidContent</Link>
        </li>
        <li>
          <Link to="/groupchat">GroupChat</Link>
        </li>
        <li>
          <Link to="/pdfconvert">PDFConvert</Link>
        </li>
        <li>
          <Link to="/pdfedit">PdfEdit</Link>
        </li>
        <li>
          <Link to="/groups">Groups</Link>
        </li>
        <li>
          <Link to="/readermode">ReaderMode</Link>
        </li>
        <li>
          <Link to="/saveaspdf">SaveasPDF</Link>
        </li>
        <li>
          <Link to="/hashtags">Hashtags</Link>
        </li>
        <li>
          <Link to="/spellcheck">Spellcheck</Link>
        </li>
        <li>
          <Link to="/testimonials">Testimonials</Link>
        </li>
        <li>
          <Link to="/trash">Trash</Link>
        </li>
        <li>
          <Link to="/translation">Translation</Link>
        </li>
        <li>
          <Link to="/karmapoints">KarmaPoints</Link>
        </li>
        <li>
          <Link to="/watermark">Watermark</Link>
        </li>
        <li>
          <Link to="/wordlookup">Wordlookup</Link>
        </li>
        <li>
          <Link to="/wordpressexport">WordpressExport</Link>
        </li>
        <li>
          <Link to="/muteunmutechat">MuteUnmuteChat</Link>
        </li>
        <li>
          <Link to="/onlinebackup">Onlinebackup</Link>
        </li>
        <li>
          <Link to="/slideshowcreator">SlideshowCreator</Link>
        </li>
        <li>
          <Link to="/sms">SMS</Link>
        </li>
        <li>
          <Link to="/useraccount">UserAccount</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
